# Generated by Django 3.1.4 on 2021-02-01 16:26

import coordinator.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_started', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('error', models.TextField(null=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_1', models.UUIDField(null=True)),
                ('player_2', models.UUIDField(null=True)),
                ('outcome', models.TextField(default='')),
                ('winner_id', models.UUIDField(null=True)),
                ('game_type', models.IntegerField(choices=[(1, 'PLAYER_BOT'), (2, 'PLAYER_PLAYER')])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default=coordinator.models.pick_random_username, max_length=128)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
