apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuhn-poker-backend
  namespace: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuhn-poker-backend
  template:
    metadata:
      labels:
        app: kuhn-poker-backend
    spec:
      containers:
        - name: kuhn-poker-backend
          image: rg.fr-par.scw.cloud/namespace-gallant-brown/pokerbot:0.0.2
          command: 
          - /bin/bash
          - -c
          - |
            python manage.py makemigrations --settings=configurations.docker.settings
            python manage.py makemigrations coordinator --settings=configurations.docker.settings
            python manage.py migrate coordinator --settings=configurations.docker.settings
            python manage.py migrate --run-syncdb --settings=configurations.docker.settings
            python manage.py ensure_adminuser --settings=configurations.docker.settings --username=docker --email=docker@docker.com --password=docker
            python manage.py runserver 0.0.0.0:8002 --settings=configurations.docker.settings --noreload
          ports:
          - containerPort: 8000
          - containerPort: 50051
          envFrom:
          - configMapRef:
              name: django-database-config
      imagePullSecrets:
        - name: registry-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: kuhn-poker-backend
  namespace: poker
spec:
  selector:
    app: kuhn-poker-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 50051
      targetPort: 50051
  type: LoadBalancer