apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuhn-poker-backend
  namespace: poker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuhn-poker-backend
  template:
    metadata:
      labels:
        app: kuhn-poker-backend
    spec:
      initContainers:
      - name: init-db
        image: rg.fr-par.scw.cloud/namespace-gallant-brown/pokerbot:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            python manage.py makemigrations --settings=configurations.prod.settings
            python manage.py makemigrations coordinator --settings=configurations.prod.settings
            python manage.py migrate coordinator --settings=configurations.prod.settings
            python manage.py migrate --run-syncdb --settings=configurations.prod.settings
            python manage.py ensure_adminuser --settings=configurations.prod.settings --username=prod --email=prod@prod.com --password=prod
        envFrom:
        - configMapRef:
            name: kuhn-poker-config
        - secretRef:
            name: kuhn-poker-secrets
      containers:
      - name: kuhn-poker-backend
        image: rg.fr-par.scw.cloud/namespace-gallant-brown/pokerbot:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000", "--settings=configurations.prod.settings", "--noreload"]
        ports:
        - containerPort: 8000
        - containerPort: 50051
        envFrom:
        - configMapRef:
            name: kuhn-poker-config
        - secretRef:
            name: kuhn-poker-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kuhn-poker-backend
  namespace: kuhn-poker
spec:
  selector:
    app: kuhn-poker-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 50051
      targetPort: 50051
  type: LoadBalancer