apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuhn-poker-backend
  namespace: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuhn-poker-backend
  template:
    metadata:
      labels:
        app: kuhn-poker-backend
    spec:
      containers:
        - name: kuhn-poker-backend
          image: rg.fr-par.scw.cloud/namespace-gallant-brown/pokerbot:0.0.8
          command: 
            - /bin/bash
            - -c
            - |
              python manage.py makemigrations --settings=configurations.prod.settings
              python manage.py makemigrations coordinator --settings=configurations.prod.settings
              python manage.py migrate coordinator --settings=configurations.prod.settings
              python manage.py migrate --run-syncdb --settings=configurations.prod.settings
              python manage.py ensure_adminuser --settings=configurations.prod.settings --username=$ADMIN_USERNAME --email=$ADMIN_EMAIL --password=$ADMIN_PASSWORD
              python manage.py runserver 0.0.0.0:8000 --settings=configurations.prod.settings --noreload
          ports:
          - containerPort: 8000
          - containerPort: 50051
          envFrom:
          - configMapRef:
              name: django-database-config
      imagePullSecrets:
        - name: registry-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: kuhn-poker-backend
  namespace: poker
spec:
  selector:
    app: kuhn-poker-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: grpc
      port: 50051
      targetPort: 50051
  type: LoadBalancer